databases:
  - name: tasks-db
    plan: free
    databaseName: tasks_fb44
    user: tasks

services:
  - type: web
    plan: free
    name: tasks
    runtime: python
    buildCommand: './build.sh'
    # startCommand: 'python -m gunicorn tasks.asgi:application -k uvicorn.workers.UvicornWorker'
    startCommand: 'python -m gunicorn djangocrud.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT'

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasks-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4